### ISSUE TITLE
Not working with inline editor on DIV.editable

### ISSUE THREAD

**Issue by WulleBulle** [mohan/tinymce-placeholder#10]
Hallo,

first of all thank you for this plugin.
I just tried it on a div.editable. The div has a placeholder="some text" but the plugin seems to work with textareas only.

Mind to extend it to work with div.editable as well?
Would be great.

Thanks in advance.

**Comment by mohan** [comment]
This plugin is specific to tinymce. It won't work on contenteditable attribute.

May be try this - 
https://codepen.io/flesler/pen/AEIFc
or 
https://www.npmjs.com/package/contenteditable-placeholder

**Comment by WulleBulle** [comment]
Hello mohna, thanks for the reply. div.editable is the css class name of the div to activate the inline TinyMCE 4 on a div. Sorry when it wasn't clear enough.
But it is not a problem because I#ve solved it already. Sorry for not mention it here.

**Comment by mrbacay** [comment]
@WulleBulle what was the resolution?

**Comment by WulleBulle** [comment]
I use to activate the TinyMCE on Click at the editable div. Before that I am displaying a formatted placeholder Text in it. To display the placeholder in the TinyMCE I could imagine one can lay a transparent div with the placeholder text over it that gets hidden after the editor gets focused. Just a thought :D

**Comment by mrbacay** [comment]
Thanks. I actually tried that also using CSS. I just thought there was a better way.

**Comment by Septagram** [comment]
Unfortunately, this doesn't really solve the problem with the plugin: it still doesn't work in the [inline](https://www.tinymce.com/docs/get-started/use-tinymce-inline/) mode :(

@mohan If that's too difficult to fix, can you please mention this limitation in the `README`?

**Comment by Septagram** [comment]
So, I've done a little bit of research to try fixing this within the scope of the plugin, and I believe it's impossible without altering TinyMCE's behavior significantly. In the inline mode, the content area container is not created, so there's nowhere to install the label element :(

**Comment by mohan** [comment]
@Septagram I added inline mode incompatibility note in the readme.

**Comment by Septagram** [comment]
@mohan thanks )

**Comment by vivekdaryani** [comment]
@mohan can we use `editor.bodyElement` instead of `editor.getContentAreaContainer()` in inline mode.
