### ISSUE TITLE
Bold / italic / underline / strikethrough quit working when placeholder is enabled

### ISSUE THREAD

**Issue by freeads777** [mohan/tinymce-placeholder#18]
Just tested your plugin. Was surprised that it has not been pointed out to you. None of those buttons work with the plugin.

**Comment by mohan** [comment]
I added the tabbar in the test page. It is working on my Chrome and Firefox. Which browser did you see this issue?

**Comment by freeads777** [comment]
I tested it in Chrome. Not sure why it didn't work in my case. Maybe it's specific to my editor (I changed some things around in the css files and plugins).
