### ISSUE TITLE
Placeholder value is not disappearing on continuous click of bacspace

### ISSUE THREAD

**Issue by santhosh1a32** [mohan/tinymce-placeholder#19]
When I remove the content in single backspace click, the plugin will show the placeholder value. After that if i write something, the placeholder is not vanishing. The content and placeholder are overlapping

**Comment by santhosh1a32** [comment]
This is working fine , when I remove 'editor.on('setContent', onBlur);'

**Comment by olzhang** [comment]
I am creating a simple site where you can edit blog posts using tinymce. When I edit a blog post, the contents of the post are loaded into tinymce causing the editor to fire the setcontent event. If I do ``editor.on('setContent', onBlur);``, the placeholder will still be there overlayed ontop of my blog content.

So what I did instead is, I modified the onBlur function by adding this line ``!document.activeElement.isEqualNode(editor.getElement())``. So the whole onBlur function looks like this:

```javascript
function onBlur() {
    if (editor.getContent() === '' && !document.activeElement.isEqualNode(editor.getElement())) {
        label.show();
    } else {
        label.hide();
    }
}
```

Now the onBlur function will only show the placeholder if the content is empty and the user is not focused into the editor (i.e. the user is not actively editing anything in the editor)

**Comment by aguynamedben** [comment]
I implemented @santhosh1a32's fix in a pull request. @mohan can we get it reviewed and merged? Thanks for the time you put into maintaining this repo.

**Comment by aguynamedben** [comment]
I altered my approach to a more simple approach. I found that removing the onBlur() call on setContent left other edge cases. Now, I just hide the label on the 'keydown' event. See pull request for more information.

**Comment by mohan** [comment]
Works great. I merged it. Thank you. I will minify it.

New function for keydown is good, getContent (like in onBlur) doesn't get called for every keypress.

**Comment by aguynamedben** [comment]
@mohan Awesome, thanks for maintaining this helpful library. 👍
