### ISSUE TITLE
Can we use something else as a label tag for placeholder?

### ISSUE THREAD

**Issue by T0miii** [mohan/tinymce-placeholder#22]
as the title says, im having trouble using label tag as placeholder, cause i want to show some html, and this destroys all the css, so the text is not gray anymore.
![asdasd](https://cloud.githubusercontent.com/assets/10532141/18713600/2aeb26f2-8013-11e6-8869-6cb34d2f3504.PNG)

**Comment by mohan** [comment]
Pass placeholder_tag property to change the type of tag. I updated the test.html file with this example.
